//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.05 at 03:18:59 PM EDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://downloads.jboss.org/overlord/dtgov/schemas/task-api-v1.xsd", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.overlord.dtgov.taskapi.types;
