//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.10 at 02:58:42 PM EDT 
//


package org.overlord.dtgov.taskapi.types;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="status" type="{http://downloads.jboss.org/overlord/dtgov/schemas/task-api-v1.xsd}statusType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="priority" type="{http://www.w3.org/2001/XMLSchema}int" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="dueOnFrom" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="dueOnTo" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="startIndex" type="{http://www.w3.org/2001/XMLSchema}int" default="0" />
 *       &lt;attribute name="endIndex" type="{http://www.w3.org/2001/XMLSchema}int" default="19" />
 *       &lt;attribute name="orderBy" type="{http://www.w3.org/2001/XMLSchema}string" default="priority" />
 *       &lt;attribute name="orderAscending" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "status",
    "priority",
    "dueOnFrom",
    "dueOnTo"
})
@XmlRootElement(name = "findTasksRequest")
public class FindTasksRequest
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    protected List<StatusType> status;
    @XmlElement(type = Integer.class)
    protected List<Integer> priority;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar dueOnFrom;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar dueOnTo;
    @XmlAttribute(name = "startIndex")
    protected Integer startIndex;
    @XmlAttribute(name = "endIndex")
    protected Integer endIndex;
    @XmlAttribute(name = "orderBy")
    protected String orderBy;
    @XmlAttribute(name = "orderAscending")
    protected Boolean orderAscending;

    /**
     * Gets the value of the status property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the status property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStatus().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link StatusType }
     * 
     * 
     */
    public List<StatusType> getStatus() {
        if (status == null) {
            status = new ArrayList<StatusType>();
        }
        return this.status;
    }

    /**
     * Gets the value of the priority property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the priority property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPriority().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Integer }
     * 
     * 
     */
    public List<Integer> getPriority() {
        if (priority == null) {
            priority = new ArrayList<Integer>();
        }
        return this.priority;
    }

    /**
     * Gets the value of the dueOnFrom property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDueOnFrom() {
        return dueOnFrom;
    }

    /**
     * Sets the value of the dueOnFrom property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDueOnFrom(XMLGregorianCalendar value) {
        this.dueOnFrom = value;
    }

    /**
     * Gets the value of the dueOnTo property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDueOnTo() {
        return dueOnTo;
    }

    /**
     * Sets the value of the dueOnTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDueOnTo(XMLGregorianCalendar value) {
        this.dueOnTo = value;
    }

    /**
     * Gets the value of the startIndex property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getStartIndex() {
        if (startIndex == null) {
            return  0;
        } else {
            return startIndex;
        }
    }

    /**
     * Sets the value of the startIndex property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setStartIndex(Integer value) {
        this.startIndex = value;
    }

    /**
     * Gets the value of the endIndex property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getEndIndex() {
        if (endIndex == null) {
            return  19;
        } else {
            return endIndex;
        }
    }

    /**
     * Sets the value of the endIndex property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setEndIndex(Integer value) {
        this.endIndex = value;
    }

    /**
     * Gets the value of the orderBy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrderBy() {
        if (orderBy == null) {
            return "priority";
        } else {
            return orderBy;
        }
    }

    /**
     * Sets the value of the orderBy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrderBy(String value) {
        this.orderBy = value;
    }

    /**
     * Gets the value of the orderAscending property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isOrderAscending() {
        if (orderAscending == null) {
            return false;
        } else {
            return orderAscending;
        }
    }

    /**
     * Sets the value of the orderAscending property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setOrderAscending(Boolean value) {
        this.orderAscending = value;
    }

}
