//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.10 at 02:58:42 PM EDT 
//


package org.overlord.dtgov.taskapi.types;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for statusType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="statusType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Created"/>
 *     &lt;enumeration value="Ready"/>
 *     &lt;enumeration value="Reserved"/>
 *     &lt;enumeration value="InProgress"/>
 *     &lt;enumeration value="Completed"/>
 *     &lt;enumeration value="Failed"/>
 *     &lt;enumeration value="Error"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "statusType")
@XmlEnum
public enum StatusType {

    @XmlEnumValue("Created")
    CREATED("Created"), //$NON-NLS-1$
    @XmlEnumValue("Ready")
    READY("Ready"), //$NON-NLS-1$
    @XmlEnumValue("Reserved")
    RESERVED("Reserved"), //$NON-NLS-1$
    @XmlEnumValue("InProgress")
    IN_PROGRESS("InProgress"), //$NON-NLS-1$
    @XmlEnumValue("Completed")
    COMPLETED("Completed"), //$NON-NLS-1$
    @XmlEnumValue("Failed")
    FAILED("Failed"), //$NON-NLS-1$
    @XmlEnumValue("Error")
    ERROR("Error"); //$NON-NLS-1$
    private final String value;

    StatusType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static StatusType fromValue(String v) {
        for (StatusType c: StatusType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
